- name: 紹介
  url: ./introduction.md
- name: 始め方
  content:
    - name: スクリプト参照
      url: ./script-reference.md
    - name: 最初のアプリケーションを作成
      url: ./create-first-app.md
- name: クイックスタート
  url: ./quick-start.md
- name: テンプレート構文
  content:
    - name: コンテンツレンダリング
      url: ./content-rendering.md
    - name: イベントバインディング
      url: ./event-binding.md
    - name: プロパティレスポンス
      url: ./property-response.md
    - name: プロパティバインディング
      url: ./property-binding.md
    - name: クラス・スタイルバインディング
      url: ./class-style-binding.md
    - name: 条件付きレンダリング
      url: ./conditional-rendering.md
    - name: リストレンダリング
      url: ./list-rendering.md
    - name: 算出プロパティ
      url: ./computed-properties.md
    - name: ウォッチャー
      url: ./watchers.md
    - name: ライフサイクル
      url: ./lifecycle.md
- name: コンポーネント
  content:
    - name: コンポーネント作成
      url: ./create-component.md
    - name: フィーチャープロパティの受け渡し
      url: ./inherit-attributes.md
    - name: スロット
      url: ./slots.md
    - name: ディーププロパティバインディングを理解する
      url: ./deep-property-binding.md
    - name: カスタムイベント
      url: ./custom-events.md
- name: アプリケーションとスケーラビリティ
  content:
    - name: マイクロアプリ
      url: ./micro-app.md
    - name: アプリ設定と関連関数
      url: ./app-configuration.md
    - name: シングルページアプリケーション
      url: ./routes.md
    - name: ネストされたページ/ルート
      url: ./nested-routes.md
    - name: SSR
      url: ./ssr.md
- name: 状態管理
  content:
    - name: 状態管理とは
      url: ./state-management.md
    - name: コンテキスト状態
      url: ./context-state.md
    - name: スタイルクエリ
      url: ./match-var.md
- name: ビルドとデプロイ
  url: ./build-app.md
- name: その他のコンポーネント
  content:
    - name: ホストスタイルの注入
      url: ./inject-host-style.md
    - name: 非明示コンポーネント
      url: ./non-explicit-component.md
    - name: replace-temp コンポーネント
      url: ./replace-template.md