- name: 介紹
  url: ./introduction.md
- name: 開始使用
  content:
    - name: 腳本引用
      url: ./script-reference.md
    - name: 創建第一個應用
      url: ./create-first-app.md
- name: 快速上手
  url: ./quick-start.md
- name: 模闆語法
  content:
    - name: 內容渲染
      url: ./content-rendering.md
    - name: 事件綁定
      url: ./event-binding.md
    - name: 屬性響應
      url: ./property-response.md
    - name: 屬性綁定
      url: ./property-binding.md
    - name: 類和樣式綁定
      url: ./class-style-binding.md
    - name: 條件渲染
      url: ./conditional-rendering.md
    - name: 列錶渲染
      url: ./list-rendering.md
    - name: 計算屬性
      url: ./computed-properties.md
    - name: 偵聽器
      url: ./watchers.md
    - name: 生命周期
      url: ./lifecycle.md
- name: 組件
  content:
    - name: 創建組件
      url: ./create-component.md
    - name: 傳遞特徵屬性
      url: ./inherit-attributes.md
    - name: 插槽
      url: ./slots.md
    - name: 領悟屬性綁定
      url: ./deep-property-binding.md
    - name: 自定義事件
      url: ./custom-events.md
- name: 應用和規模化
  content:
    - name: 微應用
      url: ./micro-app.md
    - name: 應用配置和相關函數
      url: ./app-configuration.md
    - name: 單頁面應用
      url: ./routes.md
    - name: 嵌套頁面/路由
      url: ./nested-routes.md
    - name: SSR
      url: ./ssr.md
- name: 狀態管理
  content:
    - name: 什麼是狀態管理
      url: ./state-management.md
    - name: 上下文狀態
      url: ./context-state.md
    - name: 樣式査詢
      url: ./match-var.md
- name: 生產與部署
  url: ./build-app.md
- name: 其他組件
  content:
    - name: 註入宿主樣式
      url: ./inject-host-style.md
    - name: 非顯式組件
      url: ./non-explicit-component.md
    - name: replace-temp 組件
      url: ./replace-template.md