name: ofa.js Tutorial
writingLang: cn
primaryLang: en
github: https://github.com/ofajs/ofa.js
languages:
  - cn
  - en
  - ja
  - ko
  - es
logoImg: ./logo.svg
logoName: ofa.js
googleAnalytics: >-
  <script async=""
  src="https://www.googletagmanager.com/gtag/js?id=G-7L1TCCJZT6"></script>        
  <script>           window.dataLayer = window.dataLayer || [];          
  function gtag() {             dataLayer.push(arguments);           }          
  gtag("js", new Date());            gtag("config", "G-7L1TCCJZT6");        
  </script>
