index: ./index.html
header: # 헤더에 표시될 네비게이션 주소
  - name: 튜토리얼
    url: ./documentation/_config.yaml
  - name: API
    url: ./api/_config.yaml
  - name: 기타
    content:
      - name: 시나리오 Q&A
        url: ./scenarios/_config.yaml