- name: Introducción
  url: ./introduction.md
- name: Comenzar
  content:
    - name: Referencia de script
      url: ./script-reference.md
    - name: Crear la primera aplicación
      url: ./create-first-app.md
- name: Inicio rápido
  url: ./quick-start.md
- name: Sintaxis de plantilla
  content:
    - name: Renderizado de contenido
      url: ./content-rendering.md
    - name: Enlace de eventos
      url: ./event-binding.md
    - name: Respuesta de propiedades
      url: ./property-response.md
    - name: Enlace de propiedades
      url: ./property-binding.md
    - name: Enlace de clases y estilos
      url: ./class-style-binding.md
    - name: Renderizado condicional
      url: ./conditional-rendering.md
    - name: Renderizado de listas
      url: ./list-rendering.md
    - name: Propiedades computadas
      url: ./computed-properties.md
    - name: Observadores
      url: ./watchers.md
    - name: Ciclo de vida
      url: ./lifecycle.md
- name: Componentes
  content:
    - name: Crear componentes
      url: ./create-component.md
    - name: Pasar atributos heredados
      url: ./inherit-attributes.md
    - name: Slots
      url: ./slots.md
    - name: Enlace profundo de propiedades
      url: ./deep-property-binding.md
    - name: Eventos personalizados
      url: ./custom-events.md
- name: Aplicaciones y escalabilidad
  content:
    - name: Micro aplicaciones
      url: ./micro-app.md
    - name: Configuración de la aplicación y funciones relacionadas
      url: ./app-configuration.md
    - name: Aplicaciones de una sola página
      url: ./routes.md
    - name: Páginas/Rutas anidadas
      url: ./nested-routes.md
    - name: SSR
      url: ./ssr.md
- name: Gestión de estado
  content:
    - name: ¿Qué es la gestión de estado?
      url: ./state-management.md
    - name: Estado de contexto
      url: ./context-state.md
    - name: Consulta de estilos
      url: ./match-var.md
- name: Producción y despliegue
  url: ./build-app.md
- name: Otros componentes
  content:
    - name: Inyectar estilos del host
      url: ./inject-host-style.md
    - name: Componentes no explícitos
      url: ./non-explicit-component.md
    - name: Componente replace-temp
      url: ./replace-template.md