- name: Introduction
  url: ./introduction.md
- name: Commencer
  content:
    - name: Référence du script
      url: ./script-reference.md
    - name: Créer votre première application
      url: ./create-first-app.md
- name: Démarrage rapide
  url: ./quick-start.md
- name: Syntaxe des modèles
  content:
    - name: Rendu de contenu
      url: ./content-rendering.md
    - name: Liaison d'événements
      url: ./event-binding.md
    - name: Réactivité des propriétés
      url: ./property-response.md
    - name: Liaison de propriétés
      url: ./property-binding.md
    - name: Liaison de classes et styles
      url: ./class-style-binding.md
    - name: Rendu conditionnel
      url: ./conditional-rendering.md
    - name: Rendu de liste
      url: ./list-rendering.md
    - name: Propriétés calculées
      url: ./computed-properties.md
    - name: Observateurs
      url: ./watchers.md
    - name: Cycle de vie
      url: ./lifecycle.md
- name: Composants
  content:
    - name: Créer un composant
      url: ./create-component.md
    - name: Transmission d'attributs
      url: ./inherit-attributes.md
    - name: Slots
      url: ./slots.md
    - name: Liaison de propriétés profondes
      url: ./deep-property-binding.md
    - name: Événements personnalisés
      url: ./custom-events.md
- name: Applications et mise à l'échelle
  content:
    - name: Micro-applications
      url: ./micro-app.md
    - name: Configuration de l'application et fonctions associées
      url: ./app-configuration.md
    - name: Applications monopages
      url: ./routes.md
    - name: Routes/pages imbriquées
      url: ./nested-routes.md
    - name: SSR
      url: ./ssr.md
- name: Gestion d'état
  content:
    - name: Qu'est-ce que la gestion d'état
      url: ./state-management.md
    - name: État du contexte
      url: ./context-state.md
    - name: Requêtes de style
      url: ./match-var.md
- name: Production et déploiement
  url: ./build-app.md
- name: Autres composants
  content:
    - name: Injection de styles hôtes
      url: ./inject-host-style.md
    - name: Composants non explicites
      url: ./non-explicit-component.md
    - name: Composant replace-template
      url: ./replace-template.md