index: ./index.html
header: # Navigation addresses displayed on headers
  - name: Tutorial
    url: ./documentation/_config.yaml
  - name: API
    url: ./api/_config.yaml
  - name: Others
    content:
      - name: Scenarios & Q&A
        url: ./scenarios/_config.yaml