index: ./index.html
header: # Direcciones de navegación que se muestran en los headers
  - name: Tutorial
    url: ./documentation/_config.yaml
  - name: API
    url: ./api/_config.yaml
  - name: Otros
    content:
      - name: Preguntas y respuestas de escenarios
        url: ./scenarios/_config.yaml