- name: 소개
  url: ./introduction.md
- name: 시작하기
  content:
    - name: 스크립트 참조
      url: ./script-reference.md
    - name: 첫 번째 앱 만들기
      url: ./create-first-app.md
- name: 빠른 시작
  url: ./quick-start.md
- name: 템플릿 문법
  content:
    - name: 내용 렌더링
      url: ./content-rendering.md
    - name: 이벤트 바인딩
      url: ./event-binding.md
    - name: 속성 반응
      url: ./property-response.md
    - name: 속성 바인딩
      url: ./property-binding.md
    - name: 클래스 및 스타일 바인딩
      url: ./class-style-binding.md
    - name: 조건부 렌더링
      url: ./conditional-rendering.md
    - name: 목록 렌더링
      url: ./list-rendering.md
    - name: 계산된 속성
      url: ./computed-properties.md
    - name: 감시자
      url: ./watchers.md
    - name: 생명주기
      url: ./lifecycle.md
- name: 컴포넌트
  content:
    - name: 컴포넌트 생성
      url: ./create-component.md
    - name: 상속 속성 전달
      url: ./inherit-attributes.md
    - name: 슬롯
      url: ./slots.md
    - name: 깊은 속성 바인딩
      url: ./deep-property-binding.md
    - name: 사용자 정의 이벤트
      url: ./custom-events.md
- name: 애플리케이션 및 확장
  content:
    - name: 마이크로 앱
      url: ./micro-app.md
    - name: 앱 구성 및 관련 함수
      url: ./app-configuration.md
    - name: 단일 페이지 애플리케이션
      url: ./routes.md
    - name: 중첩 페이지/라우트
      url: ./nested-routes.md
    - name: SSR
      url: ./ssr.md
- name: 상태 관리
  content:
    - name: 상태 관리란 무엇인가
      url: ./state-management.md
    - name: 컨텍스트 상태
      url: ./context-state.md
    - name: 스타일 쿼리
      url: ./match-var.md
- name: 빌드 및 배포
  url: ./build-app.md
- name: 기타 컴포넌트
  content:
    - name: 호스트 스타일 주입
      url: ./inject-host-style.md
    - name: 비명시적 컴포넌트
      url: ./non-explicit-component.md
    - name: replace-temp 컴포넌트
      url: ./replace-template.md