- name: Einführung
  url: ./introduction.md
- name: Erste Schritte
  content:
    - name: Skriptreferenz
      url: ./script-reference.md
    - name: Erste App erstellen
      url: ./create-first-app.md
- name: Schnellstart
  url: ./quick-start.md
- name: Vorlagensyntax
  content:
    - name: Inhaltswiedergabe
      url: ./content-rendering.md
    - name: Ereignisbindung
      url: ./event-binding.md
    - name: Eigenschaftsreaktion
      url: ./property-response.md
    - name: Eigenschaftsbindung
      url: ./property-binding.md
    - name: Klassen- und Stilbindung
      url: ./class-style-binding.md
    - name: Bedingte Darstellung
      url: ./conditional-rendering.md
    - name: Listendarstellung
      url: ./list-rendering.md
    - name: Berechnete Eigenschaften
      url: ./computed-properties.md
    - name: Beobachter
      url: ./watchers.md
    - name: Lebenszyklus
      url: ./lifecycle.md
- name: Komponenten
  content:
    - name: Komponente erstellen
      url: ./create-component.md
    - name: Vererbte Attribute übergeben
      url: ./inherit-attributes.md
    - name: Slots
      url: ./slots.md
    - name: Tiefe Eigenschaftsbindung
      url: ./deep-property-binding.md
    - name: Benutzerdefinierte Ereignisse
      url: ./custom-events.md
- name: Anwendung und Skalierung
  content:
    - name: Mikro-App
      url: ./micro-app.md
    - name: App-Konfiguration und zugehörige Funktionen
      url: ./app-configuration.md
    - name: Einzelseiten-Anwendung
      url: ./routes.md
    - name: Verschachtelte Seiten/Routen
      url: ./nested-routes.md
    - name: SSR
      url: ./ssr.md
- name: Zustandsverwaltung
  content:
    - name: Was ist Zustandsverwaltung?
      url: ./state-management.md
    - name: Kontextzustand
      url: ./context-state.md
    - name: Stilabfrage
      url: ./match-var.md
- name: Produktion und Bereitstellung
  url: ./build-app.md
- name: Andere Komponenten
  content:
    - name: Host-Stile einfügen
      url: ./inject-host-style.md
    - name: Nicht explizite Komponente
      url: ./non-explicit-component.md
    - name: replace-temp Komponente
      url: ./replace-template.md