- name: Introduction
  url: ./introduction.md
- name: Getting Started
  content:
    - name: Script Reference
      url: ./script-reference.md
    - name: Create Your First App
      url: ./create-first-app.md
- name: Quick Start
  url: ./quick-start.md
- name: Template Syntax
  content:
    - name: Content Rendering
      url: ./content-rendering.md
    - name: Event Binding
      url: ./event-binding.md
    - name: Property Reactivity
      url: ./property-response.md
    - name: Property Binding
      url: ./property-binding.md
    - name: Class and Style Binding
      url: ./class-style-binding.md
    - name: Conditional Rendering
      url: ./conditional-rendering.md
    - name: List Rendering
      url: ./list-rendering.md
    - name: Computed Properties
      url: ./computed-properties.md
    - name: Watchers
      url: ./watchers.md
    - name: Lifecycle
      url: ./lifecycle.md
- name: Components
  content:
    - name: Creating Components
      url: ./create-component.md
    - name: Inheriting Attributes
      url: ./inherit-attributes.md
    - name: Slots
      url: ./slots.md
    - name: Deep Property Binding
      url: ./deep-property-binding.md
    - name: Custom Events
      url: ./custom-events.md
- name: Application & Scaling
  content:
    - name: Micro Apps
      url: ./micro-app.md
    - name: App Configuration & Related Functions
      url: ./app-configuration.md
    - name: Single Page Application
      url: ./routes.md
    - name: Nested Pages/Routes
      url: ./nested-routes.md
    - name: SSR
      url: ./ssr.md
- name: State Management
  content:
    - name: What is State Management
      url: ./state-management.md
    - name: Context State
      url: ./context-state.md
    - name: Style Queries
      url: ./match-var.md
- name: Production & Deployment
  url: ./build-app.md
- name: Other Components
  content:
    - name: Inject Host Styles
      url: ./inject-host-style.md
    - name: Non-Explicit Components
      url: ./non-explicit-component.md
    - name: replace-temp Component
      url: ./replace-template.md