index: ./index.html
header: # Adresse de navigation affichée dans les en-têtes
  - name: Tutoriel
    url: ./documentation/_config.yaml
  - name: API
    url: ./api/_config.yaml
  - name: Autres
    content:
      - name: Scénarios de questions-réponses
        url: ./scenarios/_config.yaml