- name: 介绍
  url: ./introduction.md
- name: 开始使用
  content:
    - name: 脚本引用
      url: ./script-reference.md
    - name: 创建第一个应用
      url: ./create-first-app.md
- name: 快速上手
  url: ./quick-start.md
- name: 模板语法
  content:
    - name: 内容渲染
      url: ./content-rendering.md
    - name: 事件绑定
      url: ./event-binding.md
    - name: 属性响应
      url: ./property-response.md
    - name: 属性绑定
      url: ./property-binding.md
    - name: 类和样式绑定
      url: ./class-style-binding.md
    - name: 条件渲染
      url: ./conditional-rendering.md
    - name: 列表渲染
      url: ./list-rendering.md
    - name: 计算属性
      url: ./computed-properties.md
    - name: 侦听器
      url: ./watchers.md
    - name: 生命周期
      url: ./lifecycle.md
- name: 组件
  content:
    - name: 创建组件
      url: ./create-component.md
    - name: 传递特征属性
      url: ./inherit-attributes.md
    - name: 插槽
      url: ./slots.md
    - name: 领悟属性绑定
      url: ./deep-property-binding.md
    - name: 自定义事件
      url: ./custom-events.md
- name: 应用和规模化
  content:
    - name: 微应用
      url: ./micro-app.md
    - name: 应用配置和相关函数
      url: ./app-configuration.md
    - name: 单页面应用
      url: ./routes.md
    - name: 嵌套页面/路由
      url: ./nested-routes.md
    - name: SSR
      url: ./ssr.md
- name: 状态管理
  content:
    - name: 为什么需要状态管理
      url: ./state-management.md
    - name: 共享状态
      url: ./shared-state.md
    - name: 上下文状态
      url: ./context-state.md
    - name: 样式查询
      url: ./style-query.md
- name: 生产与部署
  content:
    - name: 构建应用
      url: ./build-app.md
    - name: 部署应用
      url: ./deploy-app.md
- name: 辅助组件
  content:
    - name: 注入宿主样式
      url: ./inject-host-style.md
    - name: 非显式组件
      url: ./non-explicit-component.md